# Enable GH container registry (while this is in preview, not having this enabled will cause 403 on the Docker step)
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        
          
      - name: Build devcontainer
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: '1'
        with:
          context: ./.devcontainer
          push: false
          tags: ghcr.io/stuartleeks/gh-docker-test-devcontainer:latest
          cache-from: type=registry,ref=ghcr.io/stuartleeks/gh-docker-test-devcontainer:latest
          cache-to: type=inline
          build-args: |
            VARIANT=1.16
            INSTALL_NODE=false
            NODE_VERSION=lts/*

      - name: Perform build
        env:
          DOCKER_BUILDKIT: '1'
        run: docker run ghcr.io/stuartleeks/gh-docker-test-devcontainer:latest go build

        ## TODO - might be better just to run a script to `docker push` at this point?
      - name: Push devcontainer
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: '1'
        with:
          context: ./.devcontainer
          push: true
          tags: ghcr.io/stuartleeks/gh-docker-test-devcontainer:latest
          cache-from: type=registry,ref=ghcr.io/stuartleeks/gh-docker-test-devcontainer:latest
          cache-to: type=inline
          build-args: |
            VARIANT=1.16
            INSTALL_NODE=false
            NODE_VERSION=lts/*
